# Generated by Django 4.2.1 on 2023-05-30 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasureUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Update date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deletion date')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medidas',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Update date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deletion date')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
            ],
            options={
                'verbose_name': 'Productos',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='State')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Creation date')),
                ('updated_date', models.DateField(auto_now=True, verbose_name='Update date')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Deletion date')),
                ('description', models.CharField(max_length=50, unique=True, verbose_name='description')),
                ('measure_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='measure unit')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
    ]
